import type React from "react"
import type { Metadata } from "next"
import { Geist } from 'next/font/google'
import { AuthProvider } from "@/components/auth/auth-provider"
import { AdminProvider } from "@/components/admin/admin-provider"
import "../globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased text-white bg-neutral-950`}>
        <AuthProvider>
          <AdminProvider>{children}</AdminProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
